*The following lab was inspired in the work of Santiago Ríos Guiral (santiago.riosg@udea.edu.co), Santiago Taborda Echeverri (santiago.tabordae@udea.edu.co) and Brayan David Ramos Caicedo (brayan.ramos@udea.edu.co).*

# **Attack Classification**

In the following practice we will analyze the [UNSW-NB15](https://research.unsw.edu.au/projects/unsw-nb15-dataset) database. This database was generated with real and synthetic traffic. The .pcap files are available for its manipulation, however we will use a data set that contains per-flow characteristics of the aforementioned captures. If you want to check in detail how this database was constructed, you can check this [article](https://ieeexplore.ieee.org/abstract/document/7348942).

We will use per-flow generated features (a flow is an unidirectional sequence of packets that have some protocol-header values in common, for example, source and destination IP and ports). This is widely used in network traffic classification, since using per-packet features offer, in general, worse performances compared to its flow-based counterpart. An article explaining the differences between both type of features can be found [here](http://conferences.sigcomm.org/imc/2004/papers/p135-roughan.pdf).

In [ ]:
%%capture
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OzTpumhhK3T_juCxLSDe8D7ZuQYWjXhm' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OzTpumhhK3T_juCxLSDe8D7ZuQYWjXhm" -O UNSW_NB15_testing-set.csv && rm -rf /tmp/cookies.txt
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1I6Tp90l4qVB9Xg3gtIomsDQD2yzeG3te' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1I6Tp90l4qVB9Xg3gtIomsDQD2yzeG3te" -O UNSW_NB15_training-set.csv && rm -rf /tmp/cookies.txt
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tuXSTha6y41f-hcd4pdZhv1_7EeRrJr_' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tuXSTha6y41f-hcd4pdZhv1_7EeRrJr_" -O UNSW_NB15_complete-set.csv && rm -rf /tmp/cookies.txt
!wget -nc --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/2021.deeplearning/main/content/init.py
import init; init.init(force_download=False);

In [ ]:

import numpy as np
import pandas as pd
import statsmodels.api as sm

import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Let's import the dataset and check how it looks:

In [ ]:
df_attack=pd.read_csv("/content/UNSW_NB15_complete-set.csv")
df_attack.tail()

           id       dur proto  ... is_sm_ips_ports attack_cat  label
257668  82328  0.000005   udp  ...               0     Normal      0
257669  82329  1.106101   tcp  ...               0     Normal      0
257670  82330  0.000000   arp  ...               1     Normal      0
257671  82331  0.000000   arp  ...               1     Normal      0
257672  82332  0.000009   udp  ...               0     Normal      0

[5 rows x 45 columns]

Try to analize different characteristics of the dataset (size, number of samples per class, number of classes, feature types, measures of central tendency)

In [ ]:
df_attack['attack_cat'].value_counts()

Normal            93000
Generic           58871
Exploits          44525
Fuzzers           24246
DoS               16353
Reconnaissance    13987
Analysis           2677
Backdoor           2329
Shellcode          1511
Worms               174
Name: attack_cat, dtype: int64

In [ ]:
df_attack.dtypes

id                     int64
dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

In [ ]:
df_attack.shape

(257673, 45)

In [ ]:
df_attack.columns

Index(['id', 'dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='object')

In [ ]:
df_attack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257673 entries, 0 to 257672
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 257673 non-null  int64
 1   dur                257673 non-null  float64
 2   proto              257673 non-null  object
 3   service            257673 non-null  object
 4   state              257673 non-null  object
 5   spkts              257673 non-null  int64
 6   dpkts              257673 non-null  int64
 7   sbytes             257673 non-null  int64
 8   dbytes             257673 non-null  int64
 9   rate               257673 non-null  float64
 10  sttl               257673 non-null  int64
 11  dttl               257673 non-null  int64
 12  sload              257673 non-null  float64
 13  dload              257673 non-null  float64
 14  sloss              257673 non-null  int64
 15  dloss              257673 non-null  int64
 16  sinpkt             257673 non-null  float64
 17  dinpkt             257673 non-null  float64
 18  sjit               257673 non-null  float64
 19  djit               257673 non-null  float64
 20  swin               257673 non-null  int64
 21  stcpb              257673 non-null  int64
 22  dtcpb              257673 non-null  int64
 23  dwin               257673 non-null  int64
 24  tcprtt             257673 non-null  float64
 25  synack             257673 non-null  float64
 26  ackdat             257673 non-null  float64
 27  smean              257673 non-null  int64
 28  dmean              257673 non-null  int64
 29  trans_depth        257673 non-null  int64
 30  response_body_len  257673 non-null  int64
 31  ct_srv_src         257673 non-null  int64
 32  ct_state_ttl       257673 non-null  int64
 33  ct_dst_ltm         257673 non-null  int64
 34  ct_src_dport_ltm   257673 non-null  int64
 35  ct_dst_sport_ltm   257673 non-null  int64
 36  ct_dst_src_ltm     257673 non-null  int64
 37  is_ftp_login       257673 non-null  int64
 38  ct_ftp_cmd         257673 non-null  int64
 39  ct_flw_http_mthd   257673 non-null  int64
 40  ct_src_ltm         257673 non-null  int64
 41  ct_srv_dst         257673 non-null  int64
 42  is_sm_ips_ports    257673 non-null  int64
 43  attack_cat         257673 non-null  object
 44  label              257673 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 88.5+ MB

In [ ]:
df_attack.describe()

                  id            dur  ...  is_sm_ips_ports          label
count  257673.000000  257673.000000  ...    257673.000000  257673.000000
mean    72811.823858       1.246715  ...         0.014274       0.639077
std     48929.917641       5.974305  ...         0.118618       0.480269
min         1.000000       0.000000  ...         0.000000       0.000000
25%     32210.000000       0.000008  ...         0.000000       0.000000
50%     64419.000000       0.004285  ...         0.000000       1.000000
75%    110923.000000       0.685777  ...         0.000000       1.000000
max    175341.000000      59.999989  ...         1.000000       1.000000

[8 rows x 41 columns]

A good practice is to check how disperse are the features, analyze its skewness and identify outliers. Boxplots are good tools to check this, try to select different features and plot them. Since we are dealing with different types of attacks, is recommended that you generate a boxplot per each feature related to each label. For example, if you want to analyze the feature *smean*, you should draw 10 boxplots (9 for all the attack types and 1 for the normal traffic). Draw your own conclusions.

In [ ]:
training_DB = pd.read_csv("/content/UNSW_NB15_complete-set.csv", index_col=0)
df_analysis = pd.DataFrame({'dload':training_DB['dload'][:] , 'label': training_DB['label'][:]})
protos = list(training_DB['proto'].unique())
protos_dict = {}

for index, proto in enumerate (protos):
    protos_dict[proto] = index

training_DB_proto = training_DB.copy()
training_DB_proto = training_DB_proto.replace(protos_dict)
training_DB_proto['proto'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132])

We recommend you to check the following features, however, you are free to choose and compare the variables you consider.

In [ ]:
features1 = ['sttl','ct_dst_src_ltm','spkts','dload','sloss','dloss','ct_src_ltm','ct_srv_dst']
features2 = ['sbytes','sttl','smean','ct_dst_sport_ltm']
significant_features = ['proto','sttl','dmean','ct_dst_src_ltm','ct_dst_sport_ltm','rate','dttl','dload','dtcpb','stcpb']
feat = ['sttl','dmean','ct_dst_src_ltm','ct_dst_sport_ltm','rate','dttl','dload','dtcpb','stcpb']

#Put your code in order to graph the distributions of the variables

We will try to analyze three different problems. First, we will try to solve a two-class problem, aiming to classify normal traffic and anomalous traffic. Here is important to have in mind that the samples that are labeled as "attack" come from different types of attacks (worms, DoS, Fuzzers, among others). Then we will pick a particular attack (e.g. DDoS) and try to differentiate it from normal traffic. Finally, we will solve a multi-class problem, where we will try to simultaneously classify several attacks.

Sometimes models trained on unbalanced datasets offer poor results when used to classify unseen samples. This is because some algorithms, when receiving more data from one particular class, could be biased towards that particular group of observations, failing to understand the patterns used to distinguish among classes and leading to overfitting the bigger class. Since there is more data from the majority class, the [accuracy paradox](https://medium.com/strands-tech-corner/unbalanced-datasets-what-to-do-144e0552d9cd) can be present, since you could get a model that assign the same class to all observations.

There are different alternatives to deal with this issue, in this case we will use undersampling, trying to reduce the ratio between classes, just selecting random observations without replacement. If you want to do an "informed" undersampling, you could use a clustering technique first to retain the most of the underlying information of each class.

In [ ]:
df_attack['attack_cat'].value_counts()

Normal            93000
Generic           58871
Exploits          44525
Fuzzers           24246
DoS               16353
Reconnaissance    13987
Analysis           2677
Backdoor           2329
Shellcode          1511
Worms               174
Name: attack_cat, dtype: int64

In [ ]:
df_attack['label'].value_counts()

1    164673
0     93000
Name: label, dtype: int64

The dataset contains some categorical variables, these features can be coded and used in some particular algorithms, if you want, you can drop these columns and solve the classification problem. Further work could be trying to codify these features and choosing an algorithm that fits.

In [ ]:
df_attack_ub = df_attack.drop(columns=['id','proto','service','state'])
df_attack_ub.dtypes

dur                  float64
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

In [ ]:
df_attack_ub.head()

        dur  spkts  dpkts  ...  is_sm_ips_ports  attack_cat  label
0  0.121478      6      4  ...                0      Normal      0
1  0.649902     14     38  ...                0      Normal      0
2  1.623129      8     16  ...                0      Normal      0
3  1.681642     12     12  ...                0      Normal      0
4  0.449454     10      6  ...                0      Normal      0

[5 rows x 41 columns]

First, try to solve the two class classification problem between normal traffic (labeled as "0"), and attack samples (labeled as "1"). Here you can try to solve the problem with an unbalanced dataset and then check if there is any improvement working with a balanced dataset. We recommend you to use a 70-30 train-test split. Try to use at least two types of classifiers that can handle continuos and discrete features.

**2 Classes (normal and attack) - Unbalanced**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.model_selection import cross_val_score


#Put your logic to split the data and implement the algorithm
#Use accuracy metrics and depict the confusion matrix especially in multiclass problems

**2 Classes (normal and attack) - balanced**

In [ ]:
#We suggest you to use the following methods to undersample the data. You are also free
#to use another undersampling method (e.g. Using a clustering method)
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
under_sampler = RandomUnderSampler(random_state=42)
x_res, y_res = under_sampler.fit_resample(x_train, y_train)
x_res_test, y_res_test = under_sampler.fit_resample(x_test, y_test)

**2 Classes (normal and DDoS) - unbalanced**

In [ ]:
df2_ub = df_attack_ub.loc[(df_attack_ub['attack_cat']=='Normal') | (df_attack_ub['attack_cat']=='DoS')]
df2_ub['attack_cat'].value_counts()

Normal    93000
DoS       16353
Name: attack_cat, dtype: int64

In [ ]:
df2_ub.head()

        dur  spkts  dpkts  ...  is_sm_ips_ports  attack_cat  label
0  0.121478      6      4  ...                0      Normal      0
1  0.649902     14     38  ...                0      Normal      0
2  1.623129      8     16  ...                0      Normal      0
3  1.681642     12     12  ...                0      Normal      0
4  0.449454     10      6  ...                0      Normal      0

[5 rows x 41 columns]

**2 Classes (normal and DDoS) - balanced**

**Multiclass problem - unbalanced**

In [ ]:
df_attack_ub = df_attack.drop(columns=['id','proto','service','state','label'])
att = {'Backdoor':0, 'Analysis':1, 'Fuzzers':2, 'Shellcode':3,'Reconnaissance':4, 'Exploits':5, 'DoS':6, 'Worms':7,'Generic':8, 'Normal':9}
df3_ub = df_attack_ub
df3_ub.replace({'attack_cat':att},inplace=True)

In [ ]:
df3_ub.head()

**Multiclass problem - balanced**

**Multiclass problem - balanced - removing classes with little data**

In [ ]:
df3_ub['attack_cat'].value_counts()

In [ ]:
df_attack_ub = df_attack.drop(columns=['id','proto','service','state','label'])
df4_ub = df_attack_ub
df4_ub = df4_ub.loc[(df4_ub['attack_cat']!='Worms') & (df4_ub['attack_cat']!='Shellcode')& (df4_ub['attack_cat']!='Backdoor')& (df4_ub['attack_cat']!='Analysis')]

att = {'Backdoor':0, 'Analysis':1, 'Fuzzers':2, 'Shellcode':3,'Reconnaissance':4, 'Exploits':5, 'DoS':6, 'Worms':7,'Generic':8, 'Normal':9}
df4_ub.replace({'attack_cat':att},inplace=True)
df4_ub['attack_cat'].value_counts()

Now, pick one of the previous problems and check the results choosing the features that you consider provide the most information. Check if there is any improvement in the accuracy.

Finally read about data standarization. Check if you can apply it to any of the features. Again, draw your own conclusions.